data:
  data_root: ./data/mnist # Path to data
  train_ratio: 0.8 # Ratio of training set
  val_ratio: 0.1 # Ratio of validation set
  batch_size: 64 # How many samples per batch to load
  visualize_data_save: ./image/training_data_mnist.png

model:
  input_size: 28 # Number of expected features in the input
  hidden_size: 64 # Number of features in the hidden state
  num_layers: 1 # Number of recurrent layers
  output_size: 10 # Number of expected features in the output

train:
  num_epochs: 100 # How many epochs to use for data training
  sequence_length: 28 # Length of the input sequence
  learning_rate: 0.001 # Learning_rate
  device: cuda:0 # On which a `torch.Tensor` is or will be allocated
  save_path: ./checkpoint/mnist.pth # Path to save the trained model

log:
  sink: ./log/mnist.log # Path to save the logging file
  level: INFO # Logging level: DEBUG | INFO | WARNING | ERROR | SUCCESS | CRITICAL
  format: '{message}' # logging output format. Example: '{time:YYYY-MM-DD at HH:mm:ss} {level} {message}'
  visualize_log_save: ./image/training_log_mnist.png # Path to save the visualization result
